# *Numpy* 学习

## 1.导包

In [7]:
import numpy as np

## 2.查看属性

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组形状:', arr.shape)
print('元素个数:', arr.size)
print('数组维度：', arr.ndim)
print('元素数据类型:', arr.dtype)
print('转置:', arr.T)

[[1 2 3]
 [4 5 6]]
数组形状: (2, 3)
元素个数: 6
数组维度： 2
元素数据类型: int64
转置: [[1 4]
 [2 5]
 [3 6]]


## 3.*ndarry* 的创建

In [40]:
list1 = [1,2,3],[4,5,6]
arr = np.array(list1,dtype = np.float64) #强制类型转换
print(arr)
print(arr.ndim)

[[1. 2. 3.]
 [4. 5. 6.]]
2


### copy

In [11]:
# copy
list2 = np.copy(list1)
print(list2)
arr2 = np.copy(arr)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[[1. 2. 3.]
  [4. 5. 6.]]]


### 预定义形状

In [16]:
# 预定义形状，初始化数组
# 全0
arr3 = np.zeros_like(arr2)
print(arr3)
arr4 = np.zeros((2,4))
print(arr4)
# 全1
arr5 = np.ones_like(arr2, dtype = np.int64)
print(arr5)
# 初始化为null
arr6 = np.empty_like(arr2)
print(arr6)

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1]
  [1 1 1]]]
[[[5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324]]]


### 数列

In [25]:
# 等差数列
arr7 = np.arange(1, 6,2) #开始，结束，步长
print(arr7)

[1 3 5]


In [30]:
# 等间隔数列
arr8 = np.linspace(0,10,5,dtype = np.int64)
print(arr8)

[ 0  2  5  7 10]


### 特殊矩阵

In [35]:
# 单位矩阵
arr = np.eye(3,4,dtype=np.int64)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [49]:
# 对角矩阵
list1 = [1,2,3]
arr = np.diag(list1)
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [283]:
# 随机数组生成
## 随机浮点数（0-1）
arr = np.random.rand(2,3)
print(arr)
## 随机浮点数（指定区间）
arr2 = np.random.uniform(3,4,(2,3))
print(arr2)
## 随机整数
arr3 = np.random.randint(1,5,(2,3))
print(arr3)
## 随机数列（正态分布）
arr4 = np.random.randn(2,3)
print(arr4)

[[0.39744732 0.50353968 0.48005178]
 [0.70991876 0.01764816 0.06360523]]
[[3.11697344 3.8308852  3.30623784]
 [3.61329378 3.55355151 3.7871431 ]]
[[3 1 3]
 [2 2 2]]
[[ 0.69398746 -0.7038501  -1.02330434]
 [-2.38992006  0.46465115  0.19475632]]


In [8]:
## 设置随机种子
## 随机种子是一套固定的数学公式
## 只要种子数字一样
## 算出来的结果完全相同
np.random.seed(20)
arr5 = np.random.randint(1,5,(2,3))
print(arr5)
print(arr5)

[[4 3 4]
 [4 1 3]]
[[4 3 4]
 [4 1 3]]


## 4.*Ndarry* 的数据类型

In [14]:
## 布尔类型
list1 = [1,0,0,1]
arr = np.array(list1,dtype = np.bool)
print(arr)

## 整数类型
list2 = [1,127,0,1]
arr = np.array(list2,dtype = np.int8) #8位有符号的整数范围为-128至127
print(arr)
list2 = [1,250,0,255]
arr = np.array(list2,dtype = np.uint8) #8位无符号的整数范围为0至255
print(arr)

[ True False False  True]
[  1 127   0   1]
[  1 250   0 255]
