# *Numpy* 学习

## 1.导包

In [2]:
import numpy as np

## 2.查看属性

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组形状:', arr.shape)
print('元素个数:', arr.size)
print('数组维度：', arr.ndim)
print('元素数据类型:', arr.dtype)
print('转置:', arr.T)

[[1 2 3]
 [4 5 6]]
数组形状: (2, 3)
元素个数: 6
数组维度： 2
元素数据类型: int64
转置: [[1 4]
 [2 5]
 [3 6]]


## 3.*ndarry* 的创建

In [40]:
list1 = [1,2,3],[4,5,6]
arr = np.array(list1,dtype = np.float64) #强制类型转换
print(arr)
print(arr.ndim)

[[1. 2. 3.]
 [4. 5. 6.]]
2


### copy

In [11]:
# copy
list2 = np.copy(list1)
print(list2)
arr2 = np.copy(arr)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[[1. 2. 3.]
  [4. 5. 6.]]]


### 预定义形状

In [16]:
# 预定义形状，初始化数组
# 全0
arr3 = np.zeros_like(arr2)
print(arr3)
arr4 = np.zeros((2,4))
print(arr4)
# 全1
arr5 = np.ones_like(arr2, dtype = np.int64)
print(arr5)
# 初始化为null
arr6 = np.empty_like(arr2)
print(arr6)

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1]
  [1 1 1]]]
[[[5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324]]]


### 数列

In [25]:
# 等差数列
arr7 = np.arange(1, 6,2) #开始，结束，步长
print(arr7)

[1 3 5]


In [30]:
# 等间隔数列
arr8 = np.linspace(0,10,5,dtype = np.int64)
print(arr8)

[ 0  2  5  7 10]


### 特殊矩阵

In [35]:
# 单位矩阵
arr = np.eye(3,4,dtype=np.int64)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [49]:
# 对角矩阵
list1 = [1,2,3]
arr = np.diag(list1)
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [283]:
# 随机数组生成
## 随机浮点数（0-1）
arr = np.random.rand(2,3)
print(arr)
## 随机浮点数（指定区间）
arr2 = np.random.uniform(3,4,(2,3))
print(arr2)
## 随机整数
arr3 = np.random.randint(1,5,(2,3))
print(arr3)
## 随机数列（正态分布）
arr4 = np.random.randn(2,3)
print(arr4)

[[0.39744732 0.50353968 0.48005178]
 [0.70991876 0.01764816 0.06360523]]
[[3.11697344 3.8308852  3.30623784]
 [3.61329378 3.55355151 3.7871431 ]]
[[3 1 3]
 [2 2 2]]
[[ 0.69398746 -0.7038501  -1.02330434]
 [-2.38992006  0.46465115  0.19475632]]


In [8]:
## 设置随机种子
## 随机种子是一套固定的数学公式
## 只要种子数字一样
## 算出来的结果完全相同
np.random.seed(20)
arr5 = np.random.randint(1,5,(2,3))
print(arr5)
print(arr5)

[[4 3 4]
 [4 1 3]]
[[4 3 4]
 [4 1 3]]


## 4.*Ndarry* 的数据类型

In [15]:
## 布尔类型
list1 = [1,0,0,1]
arr = np.array(list1,dtype = np.bool)
print(arr)

## 整数类型
list2 = [1,127,0,1]
arr = np.array(list2,dtype = np.int8) #8位有符号的整数范围为-128至127
print(arr)
list2 = [1,250,0,255]
arr = np.array(list2,dtype = np.uint8) #8位无符号的整数范围为0至255
print(arr)

[ True False False  True]
[  1 127   0   1]
[  1 250   0 255]


## 5.索引与切片

In [40]:
# 一维数组的索引与切片
np.random.seed(20)
arr = np.random.randint(1,100,10) #1-100，10个随机数
print(arr)
print(arr[1])
print(arr[1:5]) #左闭右开区间
print(arr>20) #bool类型
print(arr[(arr>20) & (arr<70)]) #bool索引，&与，|或

[91 16 96 29 91 10 21 76 23 72]
16
[16 96 29 91]
[ True False  True  True  True False  True  True  True  True]
[29 21 23]


In [49]:
## 二维数组的索引与切片
np.random.seed(20)
arr = np.random.randint(1,100,(2,3)) #1-100，10个随机数
print(arr)
print(arr[1,2])

[[91 16 96]
 [29 91 10]]
10


## 6.*Ndarry* 的运算

In [3]:
## 算术运算
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b)
c = [4,5,6]
d = [7,8,9]
for i in range(0,3,1):
    print(c[i])
    print(d[i])
    d[i] = c[i] + d[i]
print(d)

[2 4 6]
4
7
5
8
6
9
[11, 13, 15]


## 7.常用函数

### 基本数学运算

In [13]:
## 平方根
# 计算平方根
print(np.sqrt(16).astype(np.int64)) # 返回的浮点
print(np.sqrt([1,4,9])) # list每个元素求算术平方根
print(np.sqrt(np.array([1,4,9]))) # ndarray的每个元素求算术平方根

4
[1. 2. 3.]
[1. 2. 3.]


In [15]:
## 指数
# 计算自然指数
print(np.exp(1)) # e的1次幂

# 计算a的b词幂
arr = np.array([1,2,3])
print(np.power(2, arr)) # 计算 2的1次幂、2次幂、3次幂
print(np.power(arr, 2)) # 计算1、2、3的2次幂

2.718281828459045
[2 4 8]
[1 4 9]


In [17]:
## 对数
# 计算自然对数
print(np.log(2.71)) # 计算e为底的对数

0.9969486348916096


In [19]:
## 三角函数
print(np.sin(np.pi / 2))
print(np.cos(np.pi))

1.0
-1.0


In [21]:
## 绝对值
arr = np.array([-1, 2, -4])
print(np.abs(arr))

[1 2 4]


In [23]:
## 检测缺失值
np.isnan([1,2, np.nan, 3])

array([False, False,  True, False])

### 统计函数

In [27]:
## 求和、平均值、最大值、最小值等
arr = np.array([1, 2, 3])

print(np.sum([1,2,3])) # 求和
print(np.mean(arr)) # 求平均值
print(np.max(arr)) # 最大值
print(np.argmax(arr)) # 最大值所在的位置
print(np.min(arr)) # 最小值
print(np.argmin(arr)) # 最小值所在的位置

6
2.0
3
2
1
0


In [29]:
## 获取标准差、方差
print(np.std([1,2,4,5,8,9])) # 标准差
print(np.var([1,2,4,5,8,9])) # 方差

2.9107081994288304
8.472222222222223


### 比较函数

In [34]:
## 数组比较大小
# 比较大于、小于、等于
arr = np.array([1,2,3,4,5,6,7])
print(arr[arr > 4])
print(arr > 4)
print(np.greater(arr, 4)) # 返回一个数组，数组值为对应元素是否大于4
print(np.less(arr, 4)) # 判断小于
print(np.equal(arr, 4)) # 判断等于

# 数组和数组比较（两个数组形状相同）
print(np.equal([3,4,5], [4,6,9])) # 返回一个数组，数组元素为两个数组的该位置元素是否相等

[5 6 7]
[False False False False  True  True  True]
[False False False False  True  True  True]
[ True  True  True False False False False]
[False False False  True False False False]
[False False False]


In [36]:
## 与或非
print(np.logical_and([1,0], [1,1]))  # 逻辑与：返回一个数组。如果两个数组对应位置的元素都为True则返回True，否则返回False
print(np.logical_or([0,0], [0,1])) # 逻辑或
print(np.logical_not([1,0])) # 逻辑非：返回一个数组，将原数组对应位置元素取非

[ True False]
[False  True]
[False  True]


In [38]:
## 检查数组元素是否为真
print(np.any([0,1,1,0])) # 返回一个布尔值：只要有一个为True，就会返回True
print(np.all([1,1,1])) # 返回一个布尔值：所有元素全部为True才返回True

True
True


### 排序函数

In [41]:
## 数组排序
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)

# 直接调用ndarray数组本身的排序函数
# 该函数没有返回值，会直接修改原数组
# arr.sort()
print(arr)

# 使用 np.sort 对数组排序，会返回一个排序好的数组，不会修改原数组的内容，
print(np.sort(arr))
print(np.argsort(arr)) # 将原数字中排序的元素的索引返回

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]


### 其他常用函数

In [53]:
## 去重
np.random.seed(0)
arr = np.random.randint(1, 100, 20)

print(np.unique(arr)) # 返回一个没有重复元素的数组，并进行了排序

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [55]:
## 数组拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1, arr2)))  # 将两个数组拼接成一个数组

[1 2 3 4 5 6]


In [56]:
## 数组切割
print(np.split(arr, 4))  # 将原始数组均匀的切分成4个数组。如果不能均匀切分会直接报错
print(np.split(arr, [6, 12, 18])) # 指定位置切分

[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32), array([71, 89, 89, 13, 59], dtype=int32), array([66, 40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]
