# *Numpy* 学习

## 1.导包

In [4]:
import numpy as np

## 2.查看属性

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组形状:', arr.shape)
print('元素个数:', arr.size)
print('数组维度：', arr.ndim)
print('元素数据类型:', arr.dtype)
print('转置:', arr.T)

[[1 2 3]
 [4 5 6]]
数组形状: (2, 3)
元素个数: 6
数组维度： 2
元素数据类型: int64
转置: [[1 4]
 [2 5]
 [3 6]]


## 3.*ndarry* 的创建

In [9]:
list1 = [1,2,3],[4,5,6]
arr = np.array([list1],dtype = np.float64) #强制类型转换
print(arr)

[[[1. 2. 3.]
  [4. 5. 6.]]]


### copy

In [11]:
# copy
list2 = np.copy(list1)
print(list2)
arr2 = np.copy(arr)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[[1. 2. 3.]
  [4. 5. 6.]]]


### 预定义形状

In [16]:
# 预定义形状，初始化数组
# 全0
arr3 = np.zeros_like(arr2)
print(arr3)
arr4 = np.zeros((2,4))
print(arr4)
# 全1
arr5 = np.ones_like(arr2, dtype = np.int64)
print(arr5)
# 初始化为null
arr6 = np.empty_like(arr2)
print(arr6)

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1]
  [1 1 1]]]
[[[5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324]]]


### 数列

In [25]:
# 等差数列
arr7 = np.arange(1, 6,2) #开始，结束，步长
print(arr7)

[1 3 5]


In [29]:
# 等间隔数列
arr8 = np.linspace(0,10,5,dtype = np.int64)
print(arr8)

[ 0  2  5  7 10]
